from pyrogram import Client

from TechlockRobot import API_ID, API_HASH, TOKEN


session_name = TOKEN.split(":")[0]
client = Client("AQC9FWDv3zgFWzjxBAFC6WESAfCGHu7bUaMHuuvZgqgErhYXL1SBfg1dfC0am-RMq2yXyTgs4OwvLSpwAHnLW60uLwPCL7KRlNHZ0BTCT6kqeUJNbFNlwbf7fOAaWSMpitlGFJTFrQRlvD5Q0gdTDHwejJcvYLqXTFo6slsKSh7ugRautvKcrhSIST3G19-B33WMSDrBmrrrZJvQXw48-u1vgObfdsxRatF0NPIQm_zat51l6aYx-hhrC4c91qVngGjkKQhM81gz1qmCA1K4IQBqBAlNEvl7wPqDr7Tk8rxqXecgSExcvDUtvTtyiKer7eBzoU68o2JG_ZCIjXHwR5R7ZdlAaAA", API_ID, API_HASH)
run = client.run
